default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "Kyle Yost"
  password: <%= Rails.application.credentials.local_mb_db_password %>
  host: localhost

development:
  <<: *default
  database: freefiredb_development

# test:
#   <<: *default
#   database: freefiredb_test

# production:
#   <<: *default
#   database: freefiredb_production
  # username: <%= ENV['FREEFIREDB_PRODUCTION_USERNAME'] %>
  # password: <%= ENV['FREEFIREDB_PRODUCTION_PASSWORD'] %>
